// Generated by js_of_ocaml 2.5
(function(B){"use strict";var
ab=224,q=1024,_=57343,Z=200,Y=400,aa=512,e=128,d="",x=" : file already exists",V=2048,W=56320,X=240,a=248,U="/",$="fd ";function
aV(a,b){var
e=a.length,d=new
Array(e+1),c=0;for(;c<e;c++)d[c]=a[c];d[c]=b;return d}function
C(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
n(c,b){if(c.fun)return n(c.fun,b);var
a=c.length,d=b.length,e=a-d;if(e==0)return c.apply(null,b);else
if(e<0)return n(c.apply(null,C(b,0,a)),C(b,a,d-a));else
return function(a){return n(c,aV(b,a))}}function
ag(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aS(a){for(var
h=d,c=h,b,j,f=0,i=a.length;f<i;f++){b=a.charCodeAt(f);if(b<e){for(var
g=f+1;g<i&&(b=a.charCodeAt(g))<e;g++);if(g-f>aa){c.substr(0,1);h+=c;c=d;h+=a.slice(f,g)}else
c+=a.slice(f,g);if(g==i)break;f=g}if(b<V){c+=String.fromCharCode(192|b>>6);c+=String.fromCharCode(e|b&63)}else
if(b<55296||b>=_)c+=String.fromCharCode(ab|b>>12,e|b>>6&63,e|b&63);else
if(b>=56319||f+1==i||(j=a.charCodeAt(f+1))<W||j>_)c+="\xef\xbf\xbd";else{f++;b=(b<<10)+j-56613888;c+=String.fromCharCode(X|b>>18,e|b>>12&63,e|b>>6&63,e|b&63)}if(c.length>q){c.substr(0,1);h+=c;c=d}}return h+c}function
aM(a,b){if(b.repeat)return b.repeat(a);var
c=d,e=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;e++;if(e==9)b.slice(0,1)}}function
A(a,b,c){var
e=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return e.apply(null,a);var
f=d;for(;0<c;b+=q,c-=q)f+=e.apply(null,C(a,b,Math.min(c,q)));return f}function
ae(a){if(a.t==2)a.c+=aM(a.l-a.c.length,"\0");else
a.c=A(a.c,0,a.c.length);a.t=0}function
aR(a){for(var
l=d,f=d,i,h,j,b,c=0,k=a.length;c<k;c++){h=a.charCodeAt(c);if(h<e){for(var
g=c+1;g<k&&(h=a.charCodeAt(g))<e;g++);if(g-c>aa){f.substr(0,1);l+=f;f=d;l+=a.slice(c,g)}else
f+=a.slice(c,g);if(g==k)break;c=g}b=1;if(++c<k&&((j=a.charCodeAt(c))&-64)==e){i=j+(h<<6);if(h<ab){b=i-12416;if(b<e)b=1}else{b=2;if(++c<k&&((j=a.charCodeAt(c))&-64)==e){i=j+(i<<6);if(h<X){b=i-925824;if(b<V||b>=55295&&b<57344)b=2}else{b=3;if(++c<k&&((j=a.charCodeAt(c))&-64)==e&&h<245){b=j-63447168+(i<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;f+="\ufffd"}else
if(b>65535)f+=String.fromCharCode(55232+(b>>10),W+(b&1023));else
f+=String.fromCharCode(b);if(f.length>q){f.substr(0,1);l+=f;f=d}}return l+f}function
aQ(a){switch(a.t){case
9:return a.c;default:ae(a);case
0:if(ag(a.c)){a.t=9;return a.c}a.t=8;case
8:return aR(a.c)}}function
h(a,b,c){this.t=a;this.c=b;this.l=c}h.prototype={toString:function(){return aQ(this)}};function
ah(a){var
b=9;if(!ag(a))b=8,a=aS(a);return new
h(b,a,a.length)}function
aW(a){var
d=a.length,c=new
Array(d);for(var
b=0;b<d;b++)c[b]=a[b];return c}function
ai(a){return function(){return arguments.length>0?n(a,aW(arguments)):n(a,[undefined])}}function
aJ(a,b){throw[0,a,b]}function
c(a){return new
h(0,a,a.length)}function
al(a,b){aJ(a,c(b))}var
f=[0];function
g(a){al(f[2],a)}function
aD(a){if(!a.opened)g("Cannot flush a closed channel");if(a.buffer==d)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=d;return 0}function
af(a){al(f[4],a)}function
o(a){if(a<0)af("String.create");return new
h(a?2:9,d,a)}function
j(a){this.data=a}j.prototype={truncate:function(){this.data=o(0)}};function
z(a){return a.l}function
ak(a){a=a
instanceof
h?a.toString():a;g(a+": No such file or directory")}var
aB=U;function
s(a){a=a
instanceof
h?a.toString():a;if(a.charCodeAt(0)!=47)a=aB+a;var
e=a.split(U),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(d);break;default:b.push(e[c]);break}b.orig=a;return b}function
m(){this.content={}}m.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
u=new
m();u.mk(d,new
m());function
y(a){var
b=u;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))ak(a.orig);b=b.get(a[c])}return b}function
aP(a){var
c=s(a),b=y(c);return b
instanceof
m?1:0}function
aN(a){return new
h(4,a,a.length)}function
ad(a){var
c=new
Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
aX(a){if(a.t!=4)ad(a);return a.c}function
aC(a,b){var
f=s(a),d=u;for(var
i=0;i<f.length-1;i++){var
e=f[i];if(!d.exists(e))d.mk(e,new
m());d=d.get(e);if(!(d
instanceof
m))g(f.orig+x)}var
e=f[f.length-1];if(d.exists(e))g(f.orig+x);if(b
instanceof
m)d.mk(e,b);else
if(b
instanceof
j)d.mk(e,b);else
if(b
instanceof
h)d.mk(e,new
j(b));else
if(b
instanceof
Array)d.mk(e,new
j(aN(b)));else
if(b.toString)d.mk(e,new
j(c(b.toString())));else
af("caml_fs_register");return 0}function
aO(a){var
b=u,d=s(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
r(a,b,c){if(f.fds===undefined)f.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?z(b.data):0;d.flags=c;f.fds[a]=d;f.fd_last_idx=a;return a}function
aY(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
h=a.toString(),j=s(a);if(d.rdonly&&d.wronly)g(h+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)g(h+" : flags Open_text and Open_binary are not compatible");if(aO(a)){if(aP(a))g(h+" : is a directory");if(d.create&&d.excl)g(h+x);var
i=f.fd_last_idx?f.fd_last_idx:0,e=y(j);if(d.truncate)e.truncate();return r(i+1,e,d)}else
if(d.create){var
i=f.fd_last_idx?f.fd_last_idx:0;aC(a,o(0));var
e=y(j);return r(i+1,e,d)}else
ak(a)}r(0,new
j(o(0)));r(1,new
j(o(0)));r(2,new
j(o(0)));function
aE(a){var
b=f.fds[a];if(b.flags.wronly)g($+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true}}function
ac(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?A(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?A(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)ad(c);var
g=a.c,h=c.c;if(a.t==4)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
aT(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=B.console;b&&b.error&&b.error(a)}function
aU(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=B.console;b&&b.log&&b.log(a)}var
t=new
Array();function
aL(a,b){var
h=c(b),d=z(h),g=z(a.file.data),f=a.offset;if(f+d>=g){var
e=o(f+d);ac(a.file.data,0,e,0,g);ac(h,0,e,f,d);a.file.data=e}a.offset+=d;return 0}function
aj(a){var
b;switch(a){case
1:b=aU;break;case
2:b=aT;break;default:b=aL}var
e=f.fds[a];if(e.flags.rdonly)g($+a+" is readonly");var
c={file:e.file,offset:e.offset,fd:a,opened:true,buffer:d,output:b};t[c.fd]=c;return c}function
aF(){var
a=0;for(var
b
in
t)if(t[b].opened)a=[0,t[b],a];return a}function
aH(a){return a
instanceof
Array?a[0]:a
instanceof
h?252:1e3}function
b(a,b){f[a+1]=b}var
aG={};function
aA(a){if((a.t&6)!=0)ae(a);return a.c}function
aK(a,b){aG[aA(a)]=b;return 0}var
aI=0;function
p(a){a[2]=aI++;return a}function
T(a,b){return a.length==1?a(b):n(a,[b])}var
D=[a,c("Invalid_argument"),-4];b(11,[a,c("Undefined_recursive_module"),-12]);b(10,[a,c("Assert_failure"),-11]);b(9,[a,c("Sys_blocked_io"),-10]);b(8,[a,c("Stack_overflow"),-9]);b(7,[a,c("Match_failure"),-8]);b(6,[a,c("Not_found"),-7]);b(5,[a,c("Division_by_zero"),-6]);b(4,[a,c("End_of_file"),-5]);b(3,D);b(2,[a,c("Failure"),-3]);b(1,[a,c("Sys_error"),-2]);b(0,[a,c("Out_of_memory"),-1]);p([a,c("Pervasives.Exit"),0]);aE(0);aj(1);aj(2);p([a,c("Array.Bottom"),0]);p([a,c("Sys.Break"),0]);p([a,c("CamlinternalFormat.Type_mismatch"),0]);var
E=[0,0],am=c("char_of_int"),at=c("Js.Error"),av=c("Dom_html.Canvas_not_available");function
F(a){E[1]=[0,a,E[1]];return 0}var
i=B,ap=null,aq=undefined;function
G(a){return 1-(a==ap?1:0)}var
H=true,as=i.Array,I=p([a,at,0]),v=[0,I,{}],ar=false,ao=aH(v)===a?v:v[0+1];aK(c("jsError"),ao);F(function(a){return a[1]===I?[0,ah(a[2].toString())]:0});F(function(a){return a
instanceof
as?0:[0,ah(a.toString())]});function
J(a){return a}function
w(d){return J(ai(function(a){if(G(J(a))){var
e=T(d,a);if(!(e|0))a.preventDefault();return e}var
c=event,b=T(d,c);if(!(b|0))c.returnValue=b;return b}))}var
aw=p([a,av,0]),au="2d";i.HTMLElement===aq;var
M=[0,0],N=[0,0],O=[0,0],P=[0,0],K=Y,L=Y,ax=[0,0];function
Q(a,b){if(0<=a)if(!(255<a)){if(122===a)ax[1]=b;var
c=a-37|0;if(3<c>>>0)return 0;switch(c){case
0:O[1]=b;return 0;case
1:M[1]=b;return 0;case
2:P[1]=b;return 0;default:N[1]=b;return 0}}throw[0,D,am]}function
ay(a){Q(a.keyCode,1);return H}function
az(a){Q(a.keyCode,0);return H}function
R(a,b,c,d,e){a.beginPath();a.moveTo(b,c);a.lineTo(b+d,c);a.lineTo(b+d,c+e);a.lineTo(b,c+e);a.closePath();return a.fill()}var
k=[0,Z],l=[0,Z];function
S(b){var
a=O[1]?k[1]-1:k[1];k[1]=a;var
c=P[1]?k[1]+1:k[1];k[1]=c;var
d=M[1]?l[1]-1:l[1];l[1]=d;var
e=N[1]?l[1]+1:l[1];l[1]=e;b.fillStyle="#ccffd9";R(b,0,0,K,L);b.fillStyle="#ff0000";R(b,k[1],l[1],50,50);i.setTimeout(ai(function(a){return S(b)}),0.15);return 0}i.onload=w(function(a){var
b=i.document.createElement("canvas");if(G(b.getContext)){b.width=K|0;b.height=L|0;i.document.body.appendChild(b);i.onkeyup=w(az);i.onkeydown=w(ay);S(b.getContext(au));return ar}throw aw});function
an(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{aD(d)}catch(f){}var
b=c;continue}return 0}}an(aF(0));return}(function(){return this}()));
